### ISSUE TITLE
submitTransaction fail

### ISSUE THREAD

**Issue by ina6ra** [dragonman225/notionapi-agent#1]
submitTransaction function fails with an error.

``{ statusCode: 400, data: { error: 'Unexpected end of JSON input' } }``

Modified not to use JSON.stringify

``
    const requestData = {
      "operations": operations
    }
``

change error

``Error: "value" required in setHeader("content-length", value)``

Add length

``
    const requestData = {
      "operations": operations,
      "length": 2,
    }
``

change error

``TypeError: First argument must be a string or Buffer``

I could not solve the problem. Please correct it.

**Comment by dragonman225** [comment]
What operations did you try to submit ?

I tried a simple one :
Change the content of a block whose `id` is `0870ee38-xxxx-xxxx-xxxx-0b5d736d7e2e` to current timestamp with yellow background.

   ```javascript
    const time = Date.now()
    const res = await agent.submitTransaction([
      {
        "id": "0870ee38-xxxx-xxxx-xxxx-0b5d736d7e2e",
        "table": "block",
        "path": ["properties", "title"],
        "command": "set",
        "args": [[time.toString(), [["h", "yellow_background"]]]]
      }
    ])
    console.log(res)
   ```

It's working.

```
{ statusCode: 200, data: {} }
```

![image](https://user-images.githubusercontent.com/25148955/66410049-0bd8f180-ea24-11e9-8675-9ffb28eb85a7.png)

**Comment by ina6ra** [comment]
Thanks, resolved. I misunderstood the value of args.
